version: '2'
services:
  web:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    command: npm run dev
    volumes:
      - .:/usr/src/nuxt-app
      - /usr/src/nuxt-app/node_modules
    ports:
      - "3000:3000"

 